<BottomNav>:
    adaptive_height: True
    spacing: 20
    padding: 10

    MDIconButton:
        icon: 'home'
    
    MDIconButton:
        icon: 'magnify'
    
    MDIconButton:
        icon: 'movie'
    
    MDIconButton:
        icon: 'heart-outline'
    
    FitImage:
        source: 'assets/images/vinayagar.jpg'
        size_hint: None, None
        size: 25, 25
        radius: [25,]
        pos_hint: {"center_x": 0.5,"center_y": 0.5}